SIGINEC/Controllers/PersonaController.cs
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SIGINEC.Controllers
{
    public class PersonaController : Controller
    {

        #region Variables y Objetos
            static string mensaje = "";
            public const int PageSize = 10;
            Menu1 menu = new Menu1();
            Menu2 menu2 = new Menu2();
            Persona persona = new Persona();
        #endregion

        public ActionResult Index()
        {
            if (Session["Usuario"] != null && Session["Perfil"].ToString() == "adm")
            {
                ViewBag.Menu1 = menu.listaMenu1();
                ViewBag.Menu2 = menu2.listarMenu2(3);
                ViewBag.Mensaje = mensaje;
                mensaje = "";

                return View(persona.listarPersonas(PageSize, 1));
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult PersonasList(int id)
        {
            return PartialView(persona.listarPersonas(PageSize, id));
        }

        public ActionResult nuevaPersona()
        {
            return View();
        }

        [HttpPost]
        public ActionResult nuevaPersona(Persona persona)
        {
            if (Session["Usuario"] != null)
            {
                if (ModelState.IsValid == true)
                {
                    persona.Nombres_Mostrar = persona.Nombre_1.Trim() + " " + persona.Apellido_1.Trim();
                    persona.GuardaPersona();
                    mensaje = "Se ha creado exitosamente la persona " + persona.Nombres_Mostrar;

                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult editaPersona(int id)
        {
            return View(persona.consPersona(id));
        }

        [HttpPost]
        public ActionResult editaPersona(Persona persona) 
        {
            if (Session["Usuario"] != null)
            {
                if (ModelState.IsValid == true)
                {
                    persona.Nombres_Mostrar = persona.Nombre_1.Trim() + " " + persona.Apellido_1.Trim();
                    persona.EditaPersona();
                    mensaje = "Se ha editado exitosamente la persona " + persona.Nombres_Mostrar;

                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public JsonResult consPersona(string documento)
        {
            return Json(persona.consPersona(documento), JsonRequestBehavior.AllowGet);
        }

    }
}

SIGINEC/Views/Persona/Index.cshtml
@model Model.Helpers.PagedData<Model.Persona>
@{
    ViewBag.Title = "Personas";
    List<Model.Menu1> lstMenu = ViewBag.Menu1;
    List<Model.Menu2> lstMenu2 = ViewBag.Menu2;
    string mensaje = ViewBag.Mensaje;
}
@section Menu1 {
    @foreach (var item in lstMenu)
    {
        if (item.pagina == "Administracion")
        {
            <li class="active"> <a href="~/@item.pagina/Index"> @item.pagina </a> </li>
        }
        else
        {
            <li> <a href="~/@item.pagina/Index"> @item.pagina </a> </li>
        }
    }
}
@section Menu2 {
    @foreach (var subP in lstMenu2)
    {
        if (subP.subPagina == "Personas")
        {
            <a href="~/Persona/Index" class="list-group-item active"> <b> @subP.subPagina </b> </a>
        }
        else if (subP.subPagina == "Usuarios")
        {
            <a href="~/Usuario/Index" class="list-group-item"> <b> @subP.subPagina </b> </a>
        }
        else if (subP.subPagina == "Clientes")
        {
            <a href="~/Cliente/Index" class="list-group-item"> <b> @subP.subPagina </b> </a>
        }
        else if (subP.subPagina == "Responsables")
        {
            <a href="~/Responsable/Index" class="list-group-item"> <b> @subP.subPagina </b> </a>
        }
    }
}
<div class="jumbotron" style="text-align:center;">
    <h2> Personas <i class="glyphicon glyphicon-globe"></i> </h2>
</div>
<div>
    <button class="btn btn-primary" id="nuevaPersona"> Nueva Persona </button>
</div>
<br />
@if (mensaje != "")
{
    <div class="alert alert-success"> <i class="glyphicon glyphicon-ok"></i> @mensaje </div>
}
<hr />
<br />
<div id="persona-list" class="container col-xs-12">
    @Html.Partial("PersonasList")
</div>

<script src="~/Assets/js/Logic.js"></script>

SIGINEC/Views/Persona/PersonasList.cshtml
@model Model.Helpers.PagedData<Model.Persona>

<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th> Id </th>
            <th> Documento </th>
            <th> Tipo Documento </th>
            <th> Nombres </th>
            <th> Email </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var per in Model.Data)
        {
            <tr>
                <td> @Html.DisplayFor(p => per.Id_Persona) </td>
                <td> @Html.DisplayFor(p => per.Numero_Documento) </td>
                <td align="center"> @Html.DisplayFor(p => per.Tipo_Documento) </td>
                <td> @Html.DisplayFor(p => per.Nombres_Mostrar)</td>
                <td> @Html.DisplayFor(p => per.Email) </td>
                <td style="text-align:right;">
                    <button type="button" alt="Editar" title="Editar" class="btn btn-warning editaPersona" data-id="@per.Id_Persona">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                    </button>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="6" style="text-align:center;">
                <ul class="pagination">
                    @for (int i = 1; i <= Model.NumberOfPages; i++)
                    {
                        if (i == Model.CurrentPage)
                        {
                            <li class="active">
                                <a class="page-persona" href="javascript:void();">@i</a>
                            </li>
                        }
                        else
                        {
                            <li>
                                <a class="page-persona" href="javascript:void();">@i</a>
                            </li>
                        }
                    }
                </ul>
            </td>
        </tr>
    </tfoot>
</table>

<script src="~/Assets/js/Logic.js"></script>

SIGINEC/Views/Persona/editaPersona.cshtml
@model Model.Persona

@{
    ViewBag.Title = "editaPersona";
    Layout = null;
}

@{Html.BeginForm("editaPersona", "Persona", FormMethod.Post);}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" style="text-align:center;">
        Edita Persona
        <i class="glyphicon glyphicon-pencil"></i>
    </h4>
</div>
<div class="modal-body">
    @Html.HiddenFor(p => p.Id_Persona)
    <div class="form-group">
        <label> Primer Nombre: </label>
        @Html.TextBoxFor(p => p.Nombre_1, new { @class = "form-control", @placeholder = "Ingrese su primer nombre" })
    </div>
    <div class="form-group">
        <label> Segundo Nombre: </label>
        @Html.TextBoxFor(p => p.Nombre_2, new { @class = "form-control", @placeholder = "Ingrese su segundo nombre" })
    </div>
    <div class="form-group">
        <label> Primer Apellido: </label>
        @Html.TextBoxFor(p => p.Apellido_1, new { @class = "form-control", @placeholder = "Ingrese su primer apellido" })
    </div>
    <div class="form-group">
        <label> Segundo Apellido: </label>
        @Html.TextBoxFor(p => p.Apellido_2, new { @class = "form-control", @placeholder = "Ingrese su segundo apellido" })
    </div>
    <div class="form-group">
        <label> Email: </label>
        @Html.TextBoxFor(p => p.Email, new { @class = "form-control", @placeholder = "Ingrese su email" })
    </div>
    <div class="form-group">
        <label> Tipo Documento: </label>
        @Html.HiddenFor(p => p.Tipo_Documento)
        @if (Model.Tipo_Documento.ToString().Trim() == "CC")
        {
            @Html.TextBox("txtTipo","Cédula de Ciudadania", new { @class = "form-control", @disabled = true }) 
        }
        else if (Model.Tipo_Documento.ToString().Trim() == "CE")
        {
             @Html.TextBox("txtTipo", "Cédula de Extranjeria", new { @class = "form-control", @disabled = true })
        }
        else if (Model.Tipo_Documento.ToString().Trim() == "TI")
        {
            @Html.TextBox("txtTipo", "Tarjeta de Identidad", new { @class = "form-control", @disabled = true })
        }
    </div>
    <div class="form-group">
        <label> No Documento: </label>
        @Html.HiddenFor(p => p.Numero_Documento)
        @Html.TextBoxFor(p => p.Numero_Documento, new { @class = "form-control", @placeholder = "Ingrese su número de documento", @disabled = true  })
    </div>
    <div class="form-group" style="color:red;">
        @Html.ValidationSummary(false, "")
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
    <button type="submit" class="btn btn-primary"> Editar </button>
</div>
@{Html.EndForm();}

@* Scripts *@
<script src="~/Assets/js/jquery.validate.min.js"></script>
<script src="~/Assets/js/jquery.validate.unobtrusive.min.js"></script>

SIGINEC/Views/Persona/nuevaPersona.cshtml
@model Model.Persona

@{
    ViewBag.Title = "nuevaPersona";
    Layout = null;
}

@{Html.BeginForm("nuevaPersona", "Persona", FormMethod.Post);}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" style="text-align:center;">
        Nueva Persona
        <i class="glyphicon glyphicon-plus"></i>
    </h4>
</div>
<div class="modal-body">
    <div class="form-group">
        <label> Primer Nombre: </label>
        @Html.TextBoxFor(p => p.Nombre_1, new { @class = "form-control", @placeholder = "Ingrese su primer nombre" })
    </div>
    <div class="form-group">
        <label> Segundo Nombre: </label>
        @Html.TextBoxFor(p => p.Nombre_2, new { @class = "form-control", @placeholder = "Ingrese su segundo nombre" })
    </div>
    <div class="form-group">
        <label> Primer Apellido: </label>
        @Html.TextBoxFor(p => p.Apellido_1, new { @class = "form-control", @placeholder = "Ingrese su primer apellido" })
    </div>
    <div class="form-group">
        <label> Segundo Apellido: </label>
        @Html.TextBoxFor(p => p.Apellido_2, new { @class = "form-control", @placeholder = "Ingrese su segundo apellido" })
    </div>
    <div class="form-group">
        <label> Tipo Documento: </label>
        @Html.DropDownListFor(p => p.Tipo_Documento, new SelectList(new[] { new SelectListItem { Value = "CC", Text = "Cédula de Ciudadania" }, new SelectListItem { Value = "CE", Text = "Cédula de Extranjeria" }, new SelectListItem { Value = "TI", Text = "Tarjeta de Identidad" } }, "Value", "Text"), "Seleccione...", new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label> No Documento: </label>
        @Html.TextBoxFor(p => p.Numero_Documento, new { @class = "form-control", @placeholder = "Ingrese su número de documento" })
    </div>
    <div class="form-group">
        <label> Email: </label>
        @Html.TextBoxFor(p => p.Email, new { @class = "form-control", @placeholder = "Ingrese su email" })
    </div>
    <div class="form-group" style="color:red;">
        <p class="validacion-persona"></p>
        @Html.ValidationSummary(false, "")
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
    <button type="submit" class="btn btn-primary"> Guardar </button>
</div>
@{Html.EndForm();}

@* Scripts *@
<script src="~/Assets/js/jquery.validate.min.js"></script>
<script src="~/Assets/js/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Assets/js/Logic.js"></script>