SIGINEC/Controllers/ResponsableController.cs
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SIGINEC.Controllers
{
    public class ResponsableController : Controller
    {
        #region Variables y Objetos
            Menu1 menu = new Menu1();
            Menu2 menu2 = new Menu2();
            Usuario usuario = new Usuario();
        #endregion

        public ActionResult Index()
        {
            if (Session["Usuario"] != null && Session["Perfil"].ToString() == "adm")
            {
                ViewBag.Menu1 = menu.listaMenu1();
                ViewBag.Menu2 = menu2.listarMenu2(3);
                ViewBag.RespBodega = usuario.traeResponsable(1);
                ViewBag.RespBajoStock = usuario.traeResponsable(2);

                return View();
            }
            else
            {
                return RedirectToAction("Indexaf", "Home");
            }
        }

        public ActionResult respBodega()
        {
            ViewBag.UsuariosBodega = usuario.listarUsuariosBodega();
            return View();
        }

        [HttpPost]
        public ActionResult respBodega(ViewRespBodega vResp)
        {
            if (Session["Usuario"] != null)
            {
                if (ModelState.IsValid == true)
                {
                    usuario.desactivaResponsable(1);
                    usuario.activaResponsable(vResp.RespBodega, 1);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult respBajoStock()
        {
            ViewBag.UsuariosBajoStock = usuario.listarUsuariosBodega();
            return View();
        }

        [HttpPost]
        public ActionResult respBajoStock(ViewRespBodega vResp)
        {
            if (Session["Usuario"] != null)
            {
                if (ModelState.IsValid == true)
                {
                    usuario.desactivaResponsable(2);
                    usuario.activaResponsable(vResp.RespBodega, 2);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

SIGINEC/Views/Responsable/Index.cshtml
@{
    ViewBag.Title = "Responsables";
    List<Model.Menu1> lstMenu = ViewBag.Menu1;
    List<Model.Menu2> lstMenu2 = ViewBag.Menu2;
    string mensaje = ViewBag.Mensaje;
}
@section Menu1 {
    @foreach (var item in lstMenu)
    {
        if (item.pagina == "Administracion")
        {
            <li class="active"> <a href="~/@item.pagina/Index"> @item.pagina </a> </li>
        }
        else
        {
            <li> <a href="~/@item.pagina/Index"> @item.pagina </a> </li>
        }
    }
}
@section Menu2 {
    @foreach (var subP in lstMenu2)
    {
        if (subP.subPagina == "Personas")
        {
            <a href="~/Persona/Index" class="list-group-item"> <b> @subP.subPagina </b> </a>
        }
        else if (subP.subPagina == "Usuarios")
        {
            <a href="~/Usuario/Index" class="list-group-item"> <b> @subP.subPagina </b> </a>
        }
        else if (subP.subPagina == "Clientes")
        {
            <a href="~/Cliente/Index" class="list-group-item"> <b> @subP.subPagina </b> </a>
        }
        else if (subP.subPagina == "Responsables")
        {
            <a href="~/Responsable/Index" class="list-group-item active"> <b> @subP.subPagina </b> </a>
        }
    }
}
<div class="jumbotron" style="text-align:center;">
    <h2> Responsables <i class=" glyphicon glyphicon-flash"></i> </h2>
</div>
<div>
    <button class="btn btn-primary" id="respBodega"> Responsable Bodega </button>
</div>
<br />
<div>
    <p>
        <b>
            @(
                ViewBag.RespBodega != null ? ViewBag.RespBodega :
                "No se ha asignado ningún resposanble de bodega"
            )
        </b>
    </p>
</div>
<br /><hr /><br />
<div>
    <button class="btn btn-primary" id="respBajoStock"> Responsable Bajo Stock </button>
</div>
<br />
<div>
    <p>
        <b>
            @(
                ViewBag.RespBajoStock != null ? ViewBag.RespBajoStock :
                "No se ha asignado ningún resposanble para solicitudes de bajo stock"
            )
        </b>
    </p>
   
</div>

<script src="~/Assets/js/Logic.js"></script>

SIGINEC/Views/Responsable/respBajoStock.cshtml
@model Model.ViewRespBodega

@{
    ViewBag.Title = "Responsable Bajo Stock";
    Layout = null;
    List<Model.UsuariosBodega> lstUsuariosB = ViewBag.UsuariosBajoStock;
}

@{Html.BeginForm("respBajoStock", "Responsable", FormMethod.Post);}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" style="text-align:center;">
        Asingar Resposanble Bajo Stock
        <i class="glyphicon glyphicon-user"></i>
    </h4>
</div>
<div class="modal-body">
    <div class="form-group">
        <label> Usuario: </label>
        @Html.DropDownListFor(u => u.RespBodega, new SelectList(lstUsuariosB, "Id_Usuario", "Nom_Usuario"), "Seleccione...", new { @class = "form-control" })
    </div>
    <div class="form-group" style="color:red;">
        @Html.ValidationSummary(false, "")
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
    <button type="submit" class="btn btn-primary"> Guardar </button>
</div>
@{Html.EndForm();}

@* Scripts *@
<script src="~/Assets/js/jquery.validate.min.js"></script>
<script src="~/Assets/js/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Assets/js/Logic.js"></script>

SIGINEC/Views/Responsable/respBodega.cshtml
@model Model.ViewRespBodega

@{
    ViewBag.Title = "Responsable Bodega";
    Layout = null;
    List<Model.UsuariosBodega> lstUsuariosB = ViewBag.UsuariosBodega;
}

@{Html.BeginForm("respBodega", "Responsable", FormMethod.Post);}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" style="text-align:center;">
        Asingar Resposanble Bodega
        <i class="glyphicon glyphicon-user"></i>
    </h4>
</div>
<div class="modal-body">
    <div class="form-group">
        <label> Usuario: </label>
        @Html.DropDownListFor(u => u.RespBodega, new SelectList(lstUsuariosB, "Id_Usuario", "Nom_Usuario"), "Seleccione...", new { @class = "form-control" })
    </div>
    <div class="form-group" style="color:red;">
        @Html.ValidationSummary(false, "")
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
    <button type="submit" class="btn btn-primary"> Guardar </button>
</div>
@{Html.EndForm();}

@* Scripts *@
<script src="~/Assets/js/jquery.validate.min.js"></script>
<script src="~/Assets/js/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Assets/js/Logic.js"></script>